defmodule Rbhicks.Repo.Migrations.CreateBlogPostTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:post_tags, primary_key: false) do
      add :post_id,
          references(:posts,
            column: :id,
            name: "post_tags_post_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "post_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:post_tags, "post_tags_post_id_fkey")

    drop constraint(:post_tags, "post_tags_tag_id_fkey")

    drop table(:post_tags)
  end
end
